/**: 
    ros__parameters:
        pages:
            - main_page
        main_page:
            name: main page
            url: "/"
            cards:
                - CartesianControlCard
            CartesianControlCard:
                name: Cartesian Control
                type: CartesianControlCard
                x_position:
                    min: 0.26
                    max: 0.42
                    step_size: 0.01
                    init: 0.3
                y_position:
                    min: -0.05
                    max: 0.05
                    step_size: 0.01
                    init: 0.0
                z_position:
                    min: -0.15
                    max: -0.1
                    step_size: 0.01
                    init: 0.03
                time_from_start:
                    min: 0.2
                    max: 5.0
                    step_size: 0.1
                    init: 1.0