/**: 
    ros__parameters:
        pages:
            - main_page
        main_page:
            name: main page
            url: "/"
            cards:
                - ImageCard
            ImageCard:
                name: Image Display
                type: ImageCard
                topic: "/camera_pre_detection/image_raw"
                compressed: false
                scale: 2