/**: 
    ros__parameters:
        pages:
            - main_page
        main_page:
            name: main page
            url: "/"
            cards:
                - PrecisionExperimentCard
            PrecisionExperimentCard:
                name: Precision Experiment
                type: PrecisionExperimentCard