/**: 
    ros__parameters:
        pages:
            - main_page
        main_page:
            name: main page
            url: "/"
            cards:
                - WeedRemovalCard
            WeedRemovalCard:
                name: Weed Removal
                type: WeedRemovalCard