/**: 
    ros__parameters:
        pages:
            - main_page
        main_page:
            name: main page
            url: "/"
            cards:
                - DiagnosticCard
            DiagnosticCard:
                name: Diagnostics
                type: DiagnosticCard

