/**: 
    ros__parameters:
        pages:
            - main_page
        main_page:
            name: main page
            url: "/"
            cards:
                - GridVisualizationCard
            GridVisualizationCard:
                name: Grid Visualization
                type: GridVisualizationCard
                odom_topic: /odom
                path_subscriber_topics: 
                  - /path
