/**: 
    ros__parameters:
        pages:
            - main_page
        main_page:
            name: main page
            url: "/"
            cards:
                - ControlCard
                - BatteryStateCard
                #- BagRecorderCard
                - LinkCard
            BatteryStateCard:
                name: Battery
                type: BatteryStateCard
                topic: "/battery_status"
            ControlCard:
                name: Controls
                type: ControlCard
                cmd_vel_topic: "/cmd_vel"
                max_speed:
                    linear: 1.0
                    angular: 1.0
                    linear_turbo: 2.0
                    angular_turbo: 2.0
            LinkCard:
                name: Links
                type: LinkCard
                links: 
                    - main_page
            BagRecorderCard:
                name: Recorder
                type: BagRecorderCard